name: "Lint"
description: Runs eslint on all files

runs:
  using: "composite"
  steps:
    - name: Install volta
      uses: volta-cli/action@v4

    - name: Cache yarn node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          **/node_modules
          node_modules
          .yarn
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Run ESLint on ALL files
      run: yarn lint-all
      shell: bash
