version: "3"

services:
  server:
    container_name: uasc-server
    ports:
      - "443:8443"
      - "80:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    # volumes:
    # - node_modules:/app/node_modules
    secrets:
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
volumes:
  node_modules:

secrets:
  NEW_RELIC_APP_NAME:
    file: ./new_relic_app_name.txt
  NEW_RELIC_LICENSE_KEY:
    file: ./new_relic_license_key.txt
