version: "3"

services:
  server:
    container_name: uasc-server
    ports:
      - "443:8000"
      - "80:8000"
    build:
      context: .
      dockerfile: ./Server.Dockerfile
    restart: always
    volumes:
      - node_modules:/app/.yarn
volumes:
  node_modules:
