name: Prettier
description: Runs prettier

runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          **/node_modules
          node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Run Prettier
      run: pnpm prettier:ci
      shell: bash
