name: Code Generation Check
description: Runs code generation check

runs:
  using: composite
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false

    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          server/node_modules
          client/node_modules
          node_modules
        key: node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Generate server code
      run: pnpm generate:types --filter server
      shell: bash

    - name: Write git diff
      run: |
        if git diff --quiet; then
          echo "SERVER_DIFF=0" >> $GITHUB_ENV
        else
          echo "SERVER_DIFF=1" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Check for differences in server code
      if: ${{ env.SERVER_DIFF != '0'}}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Your code generation for the server is not up to date. Run pnpm generate:types --filter server')

    - name: Generate client code
      run: pnpm generate:types --filter client
      shell: bash

    - name: Write git diff
      run: |
        if git diff --quiet; then
          echo "CLIENT_DIFF=0" >> $GITHUB_ENV
        else
          echo "CLIENT_DIFF=1" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Check for differences in client code
      if: ${{ env.CLIENT_DIFF != '0'}}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Your code generation for the client is not up to date. Run pnpm generate:types --filter client')
