name: "Setup Host"
description: Sets up the server that hosts client/server

inputs:
  SERVER_USERNAME:
    description: The username to use for authentication.
    required: true
  SERVER_HOST:
    description: The hostname or IP address of the server.
    required: true
  SERVER_SSH_KEY:
    description: The SSH key to use for authentication.
    required: true

runs:
  using: "composite"
  steps:
    - name: Connect via SSH and enable root access
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.SERVER_HOST }}
        username: ubuntu
        key: ${{ inputs.SERVER_SSH_KEY }}
        port: 22
        script: |
          AUTHORIZED_KEYS="/root/.ssh/authorized_keys"
          BACKUP="/root/.ssh/authorized_keys.bak"

          # Backup original authorized_keys file
          sudo cp "$AUTHORIZED_KEYS" "$BACKUP"

          sudo sed -i 's/^.*command=.*Please login as the user \\"ubuntu\\".*ssh-rsa/ssh-rsa/' "$AUTHORIZED_KEYS"

    - name: Install required dependencies
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.SERVER_HOST }}
        username: ${{ inputs.SERVER_USERNAME }}
        key: ${{ inputs.SERVER_SSH_KEY }}
        port: 22
        script: |
          #!/usr/bin/env bash
          set -e

          echo "Updating package list"
          sudo apt-get update

          echo "Install docker and docker-compose"
          sudo apt-get install -y docker.io docker-compose
          sudo usermod -aG docker $USER
          newgrp docker

          BUILDX_VERSION=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest | grep tag_name | cut -d '"' -f 4)
          mkdir -p .docker
          mkdir -p .docker/cli-plugins
          curl -L "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64" -o ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx
