name: Prettier
description: Runs prettier

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install volta
      uses: volta-cli/action@v4

    - name: Cache yarn node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: |
          **/node_modules
          node_modules
          .yarn
        key: node-modules-${{ hashFiles('yarn.lock') }}

    - name: Run Prettier
      run: yarn prettier:ci
      shell: bash
