name: Hard Sync Stable to Master

on:
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Sync stable branch with master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Hard reset stable branch to master
        run: |
          git checkout master
          git pull origin master
          git checkout stable
          git reset --hard master
          git push --force origin stable