name: Run all tests
on:
  pull_request:
  push:
    branches:
      - master

env:
  API_KEY: ${{secrets.VITE_FIREBASE_API_KEY}}

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install volta
        uses: volta-cli/action@v4

      - run: npm install -g firebase-tools

      - name: Cache yarn node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            **/node_modules
            node_modules
            .yarn
          key: node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies if cache misses
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - run: yarn test
