name: Update the google sheet with members

on:
  workflow_dispatch:
  schedule:
    # Updates every hour
    - cron: "0 * * * *"


jobs:
  update_google_sheet_members:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: google-cron-job

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        shell: bash
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            server/node_modules
            client/node_modules
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies if cache misses
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm install
        shell: bash

      - name: Update google sheet members with script
        env:
          NEXT_PUBLIC_BACKEND_BASE_URL: ${{secrets.BACKEND_BASE_URL}}
          MEMBERS_GOOGLE_SPREADSHEET_ID: ${{secrets.MEMBERS_GOOGLE_SPREADSHEET_ID}}
          MEMBERS_GOOGLE_SHEET_ID: ${{secrets.MEMBERS_GOOGLE_SHEET_ID}}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{secrets.GOOGLE_SERVICE_ACCOUNT_JSON}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
        run: |
          pnpm --prefix=server update-google-sheet-members
